<?php include('header.php') ?>
<div class="wthree-dot" style="background: rgba(0, 0, 0, 0.7);">
	<a href="<?php echo base_url(); ?>"><h1><img src="<?php echo base_url(); ?>assets/home/images/paycrypt-Logo.png"></h1></a>
	<div class="profile">
		<div class="wrap">
			<div class="content-main">
				<div class="w3ls-subscribe w3ls-subscribe1" style="padding: 3em 3em 4em; border:solid 5px #00BCD4;">
					<div class="">
						<?php 
							$userEmail=$this->session->userdata('tempEmail'); 
							if($this->session->flashdata('auth_fail_validate'))
                                {
                                  $error=$this->session->flashdata('auth_fail_validate');
                                  //echo '<span style="color:green;">'.$error.'</span>';
                                  ?>
                                  <div class="alert alert-danger alert-dismissable">
				    				<a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
				    				<strong>Warning!</strong> <?php echo $error; $this->session->unset_userdata('auth_fail_validate');?>
				  				</div>
				  				<script>setTimeout(function(){$(".alert-danger").hide("slow");},3000);</script>
                                  <?php
                                  
                                }

						?>
				    	<p class="text-center" style="font-size: 16px;">Enter the verification code generated by Google Authenticator app on your phone.
<span style="display: block;"> Enter Google Authenticator Code</span></p>
					</div>
					
					<form action="<?php echo base_url(); ?>userManager/authVerify" method="post" style="margin-top: 20px;">
						
						<input type="text" id="authCode" name="authCode" class="form-control"  placeholder="Enter Code"  style="outline: none; padding: 1.8em 1em;background: none;border: 1px solid #ffffff;color: #FFFFFF;font-size: .9em;margin: 0 0 1.5em 0;width: 75%; text-align: center; position: relative;top: 0;
						left: 4.3em;" />
									
						 <br />
						<button style="font-size: 16px; padding: 7px 100px; margin: 0px auto; text-align: center; position: relative; top: 0; left: 25%; background: #00bcd5; border: none; color: #fff;" type="submit" name="authSbt" id="authSbt">Submit</button>
					</form>
				</div>
			</div>
			
			<div class="wthree_footer_copy">
				<p>© 2018 Paycrypt. All rights reserved </p>
			</div>
		</div>
	</div>
</div>
<?php include('footer.php'); ?>